### ISSUE TITLE
Manual Is Non-Free

### ISSUE THREAD

**Issue by scott-martinez** [DavidGriffith/inform6unix#3]
The included manual is non-free. It disallows modification, and profit. Point (a) in the license notice goes against point 3 in the Debian Free Software Guidelines ("the license must allow modifications and derived works") while point (c) in the license notice goes against point 1 of the DFSG ("may not restrict any party from selling or giving away"). Can this be fixed so that the package may be included in the Debian main archives? Thank you!

"The Inform software may be freely distributed provided that: (a) distributed copies
are not substantially different from those archived by the author, (b) this and other
copyright messages are always retained in full, and (c) no profit is involved. The
same conditions apply to distribution or conversion of any electronic form of this book
which may be made available by the author. Exceptions to these conditions must be
negotiated directly with the author."

**Comment by DavidGriffith** [comment]
In August 2014, I asked Graham about this and he's pretty firm that he doesn't want to change the license on the DM4.  I will therefore remove it from this repo and instead point people to where they can download it or buy a hardcopy.  Here's what was said:

On 30 Aug 2014, at 20:56, Dave G. <dave@661.org> wrote:
> Graham...  There's one more thing that keeps Debian from including
> Inform6 in their repositories.  It's the license on the DM4 itself.
> Would you please declare a license change for this too?

No, I'm sorry; Debian's ideology isn't mine, and I disagree with it
when it comes to the authorship of books. If that means Debian
won't distribute the DM4, then - in a very small way indeed! -
that's Debian's loss.

  Graham
