### ISSUE TITLE
Tutor & Demo Licenses

### ISSUE THREAD

**Issue by scott-martinez** [DavidGriffith/inform6unix#5]
Do we know the licenses of things in tutor & demo? alice.inf for example is clear but most say nothing.

**Comment by DavidGriffith** [comment]
They are all Artistic 2.0

**Comment by scott-martinez** [comment]
Thank you, although I am not sure I understand how. The games do not explicitly say a license (alice.inf does.) It would be good if something could be added to them. Otherwise, how would people know? I understand these were written and submitted by third parties. Being that they are separate programs the license for the main program makes no requirements for them.

**Comment by DavidGriffith** [comment]
I think I was being hopeful or something.  At the very least I was irrational.  "Toyshop" was written by Graham Nelson and given an "All rights given away" license.  I emailed him and the other authors asking for explicit statements on the matter.

**Comment by DavidGriffith** [comment]
David Cornelson has declared his files to be public domain.  See 9b1d18d.  Waiting for Graham Nelson and Ethan Dicks.

**Comment by sudoman** [comment]
Are the remaining `house0?.inf` tutor files by David Cornelson unmarked because they have additional authors?

**Comment by DavidGriffith** [comment]
I've no reason to believe that the remaining house0?.inf files have authors other than David C.  I'll go ahead and mark them as public domain as well.
