### ISSUE TITLE
two minor changes to the makefile

### ISSUE THREAD

**Issue by faried** [DavidGriffith/inform6unix#7]
The first change lets me type `make -j4` -- and build with all four cores.  Because, why not build it in 1.06 seconds instead of 2.34!!!!!111eleven

Seriously, though, I got a new laptop at work and I enjoyed typing `make -j4` when installing stuff, and was surprised when it failed for this Makefile.

The second change resets the `lib` directory's contents after `make clean` by calling `git reset --hard`.  This might only be useful for Mac HFS+ (case-preserving but case-insensitive filenames).

The attachment is in a diff format.  Github wouldn't let me attach it until I renamed it to .txt.

[Makefile.txt](https://github.com/DavidGriffith/inform6unix/files/81681/Makefile.txt)

**Comment by DavidGriffith** [comment]
I applied the parallel build changes, but not the `git reset --hard`.  I can't always count on git being available.
